export const USERS_LOADING = "USERS_LOADING";
export const ADD_USERS = "ADD_USERS";
export const USERS_FAILED = "USERS_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const ADD_CAMP_REQUEST = "ADD_CAMP_REQUEST";
export const CAMP_REQUESTS_LOADING = "CAMP_REQUESTS_LOADING";
export const ADD_CAMP_REQUESTS = "ADD_CAMP_REQUESTS";
export const CAMP_REQUESTS_FAILED = "CAMP_REQUESTS_FAILED";

export const ADD_POST = 'ADD_POST';
export const ADD_POSTS = 'ADD_POSTS';
export const POSTS_FAILED = 'POSTS_FAILED';
export const POSTS_LOADING = 'POSTS_LOADING';
export const DELETE_POST = 'DELETE_POST';

export const ADD_LIKE = 'ADD_LIKE';
export const ADD_LIKES = 'ADD_LIKES';
export const LIKES_FAILED = 'LIKES_FAILED';
export const DELETE_LIKE = 'DELETE_LIKE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const ADD_HISTORY = 'ADD_HISTORY';
export const ADD_HISTORIES = 'ADD_HISTORIES';
export const HISTORIES_FAILED = 'HISTORIES_FAILED';
export const HISTORIES_LOADING = 'HISTORIES_LOADING';

export const ADD_BLOOD_REQUEST = "ADD_BLOOD_REQUEST";
export const BLOOD_REQUESTS_LOADING = "BLOOD_REQUESTS_LOADING";
export const ADD_BLOOD_REQUESTS = "ADD_BLOOD_REQUESTS";
export const BLOOD_REQUESTS_FAILED = "BLOOD_REQUESTS_FAILED";