export const USERS = [
    {
      id: 0,
      firstname: 'Bhavesh',
      lastname: 'Kumar',
      image: '/assets/images/avatar1.png',
      bloodGroup: 'O+',
      gender: 'male',
      contactnumber: '7027297692',
      email: 'bkpassi2017@gmail.com',
      address: 'Sector-12 Chandigarh India',
      disease: 'none',
      willing: true

    },
    {
        id: 1,
        firstname: 'Raj',
        lastname: 'Kumar',
        image: '/assets/images/avatar2.png',
        bloodGroup: 'O+',
        gender: 'male',
        contactnumber: '9315597692',
        email: 'kaku97692@gmail.com',
        address: 'Ambala Haryana India',
        disease: 'none',
        willing: true
    },
    {
        id: 2,
        firstname: 'Ishita',
        lastname: 'Goyal',
        image: '/assets/images/avatar3.png',
        bloodGroup: 'O+',
        gender: 'female',
        contactnumber: '1234567890',
        email: 'ishita@gmail.com',
        address: 'ambala haryana India',
        disease: 'none',
        willing: true
    },
    {
        id: 3,
        firstname: 'Aakriti',
        lastname: 'Gulati',
        image: '/assets/images/avatar4.png',
        bloodGroup: 'O+',
        gender: 'female',
        contactnumber: '2345678901',
        email: 'aakriti@gmail.com',
        address: 'Chandigarh India',
        disease: 'none',
        willing: true
    },
    {
        id: 4,
        firstname: 'Bhavesh',
        lastname: 'Kumar',
        image: '/assets/images/avatar1.png',
        bloodGroup: 'O+',
        gender: 'male',
        contactnumber: '7027297692',
        email: 'bkpassi2017@gmail.com',
        address: 'Sector-12 Chandigarh India',
        disease: 'none',
        willing: true
  
      },
      {
          id: 5,
          firstname: 'Raj',
          lastname: 'Kumar',
          image: '/assets/images/avatar2.png',
          bloodGroup: 'O+',
          gender: 'male',
          contactnumber: '9315597692',
          email: 'kaku97692@gmail.com',
          address: 'Ambala Haryana India',
          disease: 'none',
          willing: true
      },
      {
          id: 6,
          firstname: 'Ishita',
          lastname: 'Goyal',
          image: '/assets/images/avatar3.png',
          bloodGroup: 'O+',
          gender: 'female',
          contactnumber: '1234567890',
          email: 'ishita@gmail.com',
          address: 'ambala haryana India',
          disease: 'none',
          willing: true
      },
      {
          id: 7,
          firstname: 'Aakriti',
          lastname: 'Gulati',
          image: '/assets/images/avatar4.png',
          bloodGroup: 'O+',
          gender: 'female',
          contactnumber: '2345678901',
          email: 'aakriti@gmail.com',
          address: 'Chandigarh India',
          disease: 'none',
          willing: true
      },
      {
        id: 8,
        firstname: 'Bhavesh',
        lastname: 'Kumar',
        image: '/assets/images/avatar1.png',
        bloodGroup: 'O+',
        gender: 'male',
        contactnumber: '7027297692',
        email: 'bkpassi2017@gmail.com',
        address: 'Sector-12 Chandigarh India',
        disease: 'none',
        willing: true
  
      },
      {
          id: 9,
          firstname: 'Raj',
          lastname: 'Kumar',
          image: '/assets/images/avatar2.png',
          bloodGroup: 'O+',
          gender: 'male',
          contactnumber: '9315597692',
          email: 'kaku97692@gmail.com',
          address: 'Ambala Haryana India',
          disease: 'none',
          willing: true
      },
      {
          id: 10,
          firstname: 'Ishita',
          lastname: 'Goyal',
          image: '/assets/images/avatar3.png',
          bloodGroup: 'O+',
          gender: 'female',
          contactnumber: '1234567890',
          email: 'ishita@gmail.com',
          address: 'ambala haryana India',
          disease: 'none',
          willing: true
      },
      {
          id: 11,
          firstname: 'Aakriti',
          lastname: 'Gulati',
          image: '/assets/images/avatar4.png',
          bloodGroup: 'O+',
          gender: 'female',
          contactnumber: '2345678901',
          email: 'aakriti@gmail.com',
          address: 'Chandigarh India',
          disease: 'none',
          willing: true
      }
  ];